FROM flink:1.18.0

# Install Python3 and pip
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev default-jdk-headless && \
    rm -rf /var/lib/apt/lists/*

# Set Python 3 as default
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install PyFlink library
RUN JAVA_HOME=/usr/lib/jvm/default-java pip3 install apache-flink==1.18.0
