apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: go-microservices
spec:
  selector:
    app: media-service
  ports:
  - port: 8090
    targetPort: 8090
    name: webhook
  type: LoadBalancer
